"""
Curriculum for LangGraph & Agentic AI:
Sections:
1. state-graphs-nodes: State Graphs & Node Workflow Architecture (20 L1, 20 L2)
2. human-in-the-loop: Human-in-the-Loop & Interactive Breakpoints (20 L1, 20 L2)
3. multi-agent-supervision: Multi-Agent Supervision & Communication (20 L1, 20 L2)
4. memory-checkpointers: Memory, Persistence & Production Checkpointing (20 L1, 20 L2)
Total: 160 questions
"""

def get_langgraph_questions():
    questions = []
    
    sections = [
        "state-graphs-nodes",
        "human-in-the-loop",
        "multi-agent-supervision",
        "memory-checkpointers"
    ]
    
    source = {
        "source_name": "LangGraph Official Architecture & StateGraph Reference",
        "source_url": "https://langchain-ai.github.io/langgraph/concepts/high_level/",
        "publisher": "LangGraph Documentation",
        "category": "Official Documentation"
    }
    
    # 1. State Graphs & Nodes - L1 (20 questions)
    l1_state_nodes = [
        ("What is a StateGraph in LangGraph and how does it represent agent execution?",
         "A StateGraph is a stateful computation graph where nodes are Python functions that receive state and return state updates, and edges define the execution transitions.",
         "In LangGraph, a StateGraph serves as the core orchestration backbone. Unlike traditional DAGs that enforce acyclic workflows, a StateGraph naturally supports cyclical execution loops which are essential for iterative agentic reasoning. You define a TypedDict or Pydantic schema representing the shared state. When a node executes, it emits partial updates rather than overwriting the entire state. The graph compiles into a runnable object with built-in checkpointing and event streaming.",
         "StateSchema (TypedDict) -> StateGraph(StateSchema) -> add_node(name, fn) -> add_edge(from, to) -> compile()",
         "from typing import TypedDict\nfrom langgraph.graph import StateGraph, START, END\n\nclass AgentState(TypedDict):\n    input: str\n    output: str\n\ndef process_node(state: AgentState) -> dict:\n    return {'output': state['input'].upper()}\n\nbuilder = StateGraph(AgentState)\nbuilder.add_node('process', process_node)\nbuilder.add_edge(START, 'process')\nbuilder.add_edge('process', END)\ngraph = builder.compile()",
         "Evaluates basic comprehension of graph-based computation vs traditional linear chains.",
         "Checks if candidate understands how state is passed and returned in LangGraph.",
         "State schemas must be immutable in spirit; return dicts containing only keys that changed.",
         "Raising an uncaught exception in a node aborts the graph execution thread unless checkpointed.",
         "TypedDict offers lightweight zero-overhead typing while Pydantic offers runtime validation at minor compute cost.",
         ["Mutating state dictionary in-place instead of returning updates", "Assuming StateGraph cannot contain cyclic loops"]),
        
        ("Why does LangGraph require explicit Reducer functions when updating list fields?",
         "Without a reducer, returning an updated list key completely overwrites the existing list instead of appending or merging items.",
         "LangGraph states are shared dictionaries across nodes. If two nodes generate chat messages or logs, default dictionary semantics would replace the existing list with the newest return value. By using Annotated[list, operator.add] or add_messages from langgraph.graph.message, developers instruct the graph runtime to invoke the reducer function, combining incoming list elements with previous state.",
         "Node Output: {'messages': [AIMessage(content='hi')]} + Reducer (add_messages) -> Appended to State['messages']",
         "from typing import Annotated, TypedDict\nimport operator\n\nclass State(TypedDict):\n    history: Annotated[list[str], operator.add]\n\ndef step_one(state: State):\n    return {'history': ['first_step']}\n\ndef step_two(state: State):\n    return {'history': ['second_step']}",
         "Assesses whether the candidate understands state reconciliation and reducer mechanics.",
         "Verify candidate knows how to prevent accidental state clobbering in multi-turn graphs.",
         "Use built-in add_messages reducer for message history to automatically handle message IDs and deduplication.",
         "Accidentally using standard list without reducer causes message history truncation.",
         "Custom reducers allow deduplication and window trimming but increase code complexity.",
         ["Assuming LangGraph automatically appends list updates by default", "Forgetting to import Annotated from typing"]),
        
        ("What is the purpose of START and END nodes in a compiled StateGraph?",
         "START designates the entry node of the graph execution, while END designates the terminal node that concludes execution.",
         "Every compiled StateGraph requires a well-defined topological entry point and exit condition. START is a virtual node that receives initial input from invoking graph.invoke(input) and routes it to the designated first processing node. END is a virtual sink; when an execution edge points to END, graph execution completes and the final accumulated state is returned to the caller.",
         "Caller invoke() -> START virtual node -> First Node -> ... -> Last Node -> END virtual node -> Return final state",
         "from langgraph.graph import StateGraph, START, END\n\n# Adding transitions from entry to exit\nbuilder.add_edge(START, 'validate_input')\nbuilder.add_edge('generate_response', END)",
         "Tests candidate's understanding of graph lifecycle and entry/exit semantics.",
         "Ensure candidate does not use deprecated entrypoint APIs or hardcoded string literals.",
         "Always route error recovery nodes to END if recovery cannot continue to avoid infinite loops.",
         "Orphan nodes not reachable from START or not leading to END will either never run or hang.",
         "Explicit START/END makes workflow visualization unambiguous in LangGraph Studio.",
         ["Hardcoding string '__start__' instead of using the canonical START constant", "Creating unreachable disconnected nodes"]),
        
        ("How do conditional edges work in LangGraph?",
         "Conditional edges use a routing function that inspects the current state and returns the name of the next node to execute.",
         "Conditional routing allows dynamic decision-making within the graph. Instead of a static edge add_edge('nodeA', 'nodeB'), you call add_conditional_edges('nodeA', routing_function, {'action1': 'nodeB', 'action2': 'nodeC'}). The routing function accepts the current state and outputs a string routing key matching the destination mapping dictionary.",
         "Node A completes -> routing_fn(state) -> evaluates condition -> returns 'search' -> transitions to SearchNode",
         "def route_decision(state: AgentState) -> str:\n    if 'tool_calls' in state['last_message']:\n        return 'call_tool'\n    return 'finish'\n\nbuilder.add_conditional_edges('agent', route_decision, {'call_tool': 'tool_node', 'finish': END})",
         "Evaluates candidate's ability to implement branching logic and LLM router decisions.",
         "Verify understanding of dynamic state inspection and destination resolution.",
         "Keep routing functions deterministic and side-effect free; never call network APIs inside routing functions.",
         "Returning a route string not registered in the mapping dictionary causes an immediate GraphCompilationError.",
         "Using a dictionary mapping decouples router return values from concrete node names.",
         ["Executing side-effects inside the routing function", "Omitting a fallback route for unexpected outputs"]),
        
        ("What is the difference between graph.invoke() and graph.stream()?",
         "invoke() runs the graph to completion and returns the final state, while stream() yields state updates as each node finishes.",
         "In production applications, especially user-facing chatbots and interactive agents, waiting for the entire graph to finish before returning any output causes poor user experience and high latency. graph.stream(input) yields chunks of state updates, node names, or tokens in real-time, allowing frontends to render streaming responses while downstream nodes execute.",
         "stream() generator -> Node 1 finished (yield chunk) -> Node 2 finished (yield chunk) -> End",
         "for event in graph.stream({'input': 'Analyze quarterly metrics'}):\n    for node_name, state_update in event.items():\n        print(f'Node {node_name} completed with: {state_update}')",
         "Tests candidate's knowledge of synchronous vs asynchronous streaming paradigms.",
         "Ensure candidate knows how to build low-latency interactive user experiences.",
         "Always prefer stream_mode='values' or 'updates' explicitly depending on whether full state or diffs are needed.",
         "Consuming graph.stream without error handling can drop unhandled generator exceptions.",
         "Streaming adds minimal memory overhead per step compared to monolithic batch invocation.",
         ["Buffering the entire stream in memory before displaying", "Confusing node-level streaming with LLM token streaming"]),
        
        ("How does LangGraph compile() validate graph structure?",
         "compile() runs topological integrity checks, verifying all nodes are reachable, reducers are valid, and edges reference existing nodes.",
         "When compile() is called on a StateGraph builder, the framework analyzes the graph structure. It verifies that every source and target node referenced in add_edge and add_conditional_edges actually exists. It also verifies that there is at least one path from START to END, and that all specified state reducers can be resolved.",
         "GraphBuilder -> Validation checks (valid references, connectivity) -> CompiledStateGraph instance",
         "builder = StateGraph(State)\nbuilder.add_node('step1', step1_fn)\nbuilder.add_edge(START, 'step1')\nbuilder.add_edge('step1', END)\n# compile produces the immutable executable runnable\napp = builder.compile()",
         "Assesses candidate's familiarity with compilation semantics and immutable runnables.",
         "Checks if candidate understands separation of graph construction and execution phases.",
         "Compile graphs at application startup (singleton pattern) rather than recompiling on every request.",
         "Recompiling on every request introduces unnecessary CPU overhead and defeats checkpoint caching.",
         "Pre-compiling ensures graph validation happens during unit testing before production traffic hits.",
         ["Compiling graph inside request handler on every HTTP request", "Adding nodes after compile() has already been invoked"]),
        
        ("How do you pass runtime configuration parameters into graph.invoke()?",
         "Configuration is passed via the config dictionary parameter containing keys like configurable or thread_id.",
         "In production, graphs frequently need tenant IDs, database connection pools, model temperature overrides, or user credentials without polluting the primary agent state. LangGraph supports passing a config dictionary: graph.invoke(state, config={'configurable': {'model_name': 'gpt-4o', 'thread_id': 'user_123'}}). Nodes access this via the config parameter.",
         "graph.invoke(state, config={'configurable': {...}}) -> node_fn(state, config) -> extracts config['configurable']",
         "from langchain_core.runnables import RunnableConfig\n\ndef my_node(state: State, config: RunnableConfig):\n    model_name = config.get('configurable', {}).get('model_name', 'gpt-4o')\n    return {'result': f'used {model_name}'}",
         "Tests candidate's knowledge of contextual configuration separation from state data.",
         "Ensure candidate does not put operational configuration into domain state.",
         "Use configurable for credentials and runtime switches; keep business payload in state.",
         "Putting sensitive database tokens in state causes them to be permanently saved in checkpointer DB.",
         "RunnableConfig is automatically propagated across subgraphs and nested tool calls.",
         ["Putting auth tokens and DB connection pools inside the graph state schema", "Overwriting config keys directly"]),
        
        ("What is the role of ToolNode in LangGraph prebuilt components?",
         "ToolNode is a prebuilt node that inspects the latest AIMessage for tool_calls, invokes the matching tools, and returns ToolMessages.",
         "Instead of writing manual dispatch loops to execute LLM tool calls, LangGraph provides ToolNode(tools=[tool1, tool2]). It automatically extracts the tool name and arguments from the AIMessage.tool_calls array in the state, executes the Python functions asynchronously or synchronously, catches errors if configured, and constructs ToolMessage objects with results.",
         "AIMessage(tool_calls=[...]) -> ToolNode -> executes tool fn -> ToolMessage(content='result')",
         "from langgraph.prebuilt import ToolNode\nfrom langchain_core.tools import tool\n\n@tool\ndef add(a: int, b: int) -> int:\n    '''Add two numbers.'''\n    return a + b\n\ntool_node = ToolNode([add])\nbuilder.add_node('tools', tool_node)",
         "Evaluates practical knowledge of standard prebuilt tool integration patterns.",
         "Verify candidate knows how to leverage framework utilities instead of reinventing tool dispatchers.",
         "Set handle_tool_errors=True on ToolNode in production to pass error messages back to the LLM gracefully.",
         "Uncaught tool errors crash the entire agent graph without giving LLM a chance to self-correct.",
         "ToolNode executes multiple tool calls in parallel when returned by model supporting multi-tool calls.",
         ["Manually writing while loops to parse JSON tool calls", "Failing to handle tool execution timeouts"]),
        
        ("How does LangGraph represent cyclic agent workflows without stack overflow?",
         "LangGraph uses an iterative state transition loop with a configurable recursion_limit rather than recursive Python calls.",
         "Traditional recursive agents risk hitting Python's recursion limit (default 1000) and consuming excessive call stack memory. LangGraph compiles graphs into an event loop. Nodes run as sequential tasks where state updates are applied iteratively to an external state container. To prevent infinite loops, LangGraph tracks step counts and enforces recursion_limit (default 25).",
         "Event Loop: Step 1 -> Apply State -> Check recursion_limit -> Step 2 -> Apply State -> ...",
         "config = {'recursion_limit': 15}\ntry:\n    graph.invoke({'input': 'Research topic'}, config=config)\nexcept GraphRecursionError:\n    print('Agent exceeded maximum reasoning steps')",
         "Assesses candidate's understanding of iteration vs recursion and loop safeguards in agentic AI.",
         "Verify candidate knows how to tune recursion limits and catch recursion errors.",
         "Always set recursion_limit based on the maximum expected reasoning hops in production.",
         "Infinite loops with no recursion_limit will exhaust LLM budget and API rate limits.",
         "Iterative architecture allows pausing and checkpointing at any single step seamlessly.",
         ["Assuming LangGraph uses recursive function calls that blow Python stack", "Setting recursion_limit to infinity in production"]),
        
        ("What is a Subgraph in LangGraph and when should it be used?",
         "A Subgraph is an independently compiled StateGraph embedded as a node inside another parent StateGraph.",
         "Subgraphs enable modularity and separation of concerns. In complex enterprise systems, a supervisor agent might delegate specialized tasks (like data extraction, code execution, or compliance review) to specialized subgraphs. The subgraph maintains its own internal private state schema while exposing input/output mapping to the parent graph.",
         "Parent Graph Node -> invokes Subgraph.compile() -> runs internal nodes -> returns mapped output to Parent",
         "subgraph_builder = StateGraph(SubState)\n# ... define subgraph ...\nsubgraph = subgraph_builder.compile()\n\nparent_builder = StateGraph(ParentState)\nparent_builder.add_node('specialist', subgraph)",
         "Tests candidate's ability to architect hierarchical and modular agent systems.",
         "Verify candidate knows how to structure large codebases into reusable agent components.",
         "Use subgraphs when a component requires private state that parent graph does not need to persist.",
         "Misaligned input/output key schemas between parent and subgraph will cause KeyErrors.",
         "Subgraphs can be developed and unit tested independently from the primary orchestrator.",
         ["Building a giant 50-node monolithic graph instead of decomposing into subgraphs", "Sharing entire parent state with all subgraphs unnecessarily"]),
    ]

    # Fill remaining L1 state nodes questions (10 more to reach 20)
    l1_state_nodes_extra = [
        ("How do you visualize a compiled LangGraph in Python or Jupyter notebook?",
         "You can visualize a compiled graph using graph.get_graph().draw_mermaid_png() or draw_ascii().",
         "LangGraph provides built-in graph inspection tools. The method graph.get_graph() returns a Graph representation that can export Mermaid markdown or generate PNG images using Mermaid.js rendering APIs. This is essential for debugging and architectural documentation.",
         "app.get_graph().draw_mermaid() -> Mermaid text diagram",
         "from IPython.display import Image, display\ndisplay(Image(graph.get_graph().draw_mermaid_png()))",
         "Checks knowledge of developer tooling and graph introspection.",
         "Verify candidate knows how to verify graph topology visually.",
         "Export Mermaid syntax to markdown docs in CI pipelines to keep architecture diagrams updated.",
         "draw_mermaid_png requires network access to mermaid.ink unless local graphviz is configured.",
         "Mermaid is lightweight and renders natively in GitHub pull requests and Markdown files.",
         ["Assuming graphs cannot be programmatically inspected or rendered", "Using third-party external libraries to inspect node edges"]),
        
        ("What happens when multiple nodes return updates for the same state key without a reducer?",
         "The last executed node's return value will overwrite previous values for that key.",
         "When parallel branches or sequential nodes update a plain state key without an Annotated reducer, Python dictionary assignment semantics apply. The update from whichever node finishes or executes last replaces the earlier value, which can lead to silent data loss.",
         "Node 1 returns {'count': 1} -> Node 2 returns {'count': 2} -> State becomes {'count': 2}",
         "# Bad: no reducer\nclass BadState(TypedDict):\n    data: list[str]\n# Good: with reducer\nclass GoodState(TypedDict):\n    data: Annotated[list[str], operator.add]",
         "Tests understanding of race conditions and state overwrite hazards in stateful graphs.",
         "Verify candidate understands data integrity in concurrent node branches.",
         "Always define an explicit reducer if multiple nodes might execute in parallel branches.",
         "Silent overwrites in production cause lost conversational context and truncated LLM reasoning.",
         "Reducers guarantee deterministic state merging across parallel fan-outs.",
         ["Assuming LangGraph resolves key conflicts by creating tuples automatically", "Ignoring parallel branch state merging"]),
        
        ("How does LangGraph handle asynchronous node functions with async def?",
         "LangGraph natively supports async def node functions and provides ainvoke() and astream() methods.",
         "Modern Python AI backends rely heavily on async I/O to avoid blocking thread pools during long LLM API calls. LangGraph detects whether node functions are coroutines. If an async node is added, calling graph.ainvoke() or graph.astream() executes the workflow in the asyncio event loop without blocking the main thread.",
         "async def fetch_node(state): ... -> await graph.ainvoke(initial_state)",
         "async def async_node(state: State):\n    response = await async_llm.ainvoke(state['query'])\n    return {'response': response.content}\n\n# Execution: await graph.ainvoke({'query': 'hello'})",
         "Assesses candidate's mastery of asynchronous programming in Python AI services.",
         "Verify candidate knows how to prevent thread pool starvation in high-concurrency apps.",
         "Always use async def and ainvoke in FastAPI or async web servers to maximize throughput.",
         "Calling synchronous invoke() from an async route blocks the entire FastAPI event loop worker.",
         "asyncio allows concurrent execution of independent tool calls and web requests.",
         ["Mixing blocking requests.get() inside async def node functions", "Using synchronous invoke inside async web server endpoints"]),
        
        ("What is the difference between message state and generic dictionary state in LangGraph?",
         "Message state manages conversational turns with built-in deduplication, while dictionary state stores arbitrary typed variables.",
         "LangGraph provides MessagesState as a convenient base class that defines a messages key with the add_messages reducer. This reducer handles message IDs, updates existing messages when IDs match (useful for streaming edits), and supports LangChain message types (HumanMessage, AIMessage, SystemMessage). Generic dictionary state can hold any custom application domain data.",
         "MessagesState: {'messages': [HumanMessage, AIMessage]} with auto ID tracking",
         "from langgraph.graph import MessagesState\n\nclass CustomAgentState(MessagesState):\n    user_tier: str\n    retry_count: int",
         "Tests candidate's familiarity with conversation modeling and base state abstractions.",
         "Ensure candidate knows when to extend MessagesState vs creating custom TypedDicts.",
         "Subclass MessagesState when building chat applications to avoid reimplementing message reducers.",
         "Manually appending dictionaries of strings instead of Message objects breaks tool call handling.",
         "MessagesState standardizes serialization for PostgresSaver and RedisSaver checkpointers.",
         ["Reinventing message deduplication from scratch", "Storing conversation messages as plain unformatted strings"]),
        
        ("How can you pass initial state inputs into a compiled LangGraph?",
         "You pass a dictionary matching the state schema into graph.invoke(input_dict) or graph.stream(input_dict).",
         "When invoking a compiled graph, the input argument must be a dictionary. Any keys not specified in the input will either be initialized to empty/None or must have defaults if defined. The input dictionary passes through the START node directly to the first connected nodes.",
         "app.invoke({'input_key': 'value'}) -> START node initializes state -> Node 1 executes",
         "result = app.invoke({\n    'messages': [HumanMessage(content='Summarize the latest financial report.')],\n    'user_id': 'usr_9886'\n})",
         "Tests basic invocation mechanics and state parameter passing.",
         "Verify candidate knows how to initiate workflow runs correctly.",
         "Validate input dictionaries with Pydantic before passing them to graph.invoke.",
         "Passing keys that are not defined in the TypedDict schema can lead to unpredictable node behavior.",
         "TypedDict provides static type checking in IDEs and mypy linting.",
         ["Passing primitive string directly instead of a dictionary", "Forgetting to initialize required state keys"]),
        
        ("What is the Command object in LangGraph and what does it simplify?",
         "Command allows a node to return state updates and specify the next node transition in a single atomic return.",
         "In LangGraph, instead of maintaining separate conditional routing functions, a node can return Command(update={'key': 'val'}, goto='next_node'). This pattern simplifies agent control flows where the decision of what to update and where to route occurs inside the node itself (such as multi-agent handoffs).",
         "Node executes -> returns Command(update={...}, goto='verifier_node') -> graph transitions immediately",
         "from langgraph.types import Command\n\ndef triage_node(state: State) -> Command[str]:\n    if 'billing' in state['query']:\n        return Command(update={'dept': 'billing'}, goto='billing_agent')\n    return Command(update={'dept': 'tech'}, goto='tech_agent')",
         "Assesses awareness of modern LangGraph patterns for dynamic routing and multi-agent handoffs.",
         "Verify candidate understands how Command replaces verbose conditional edge mappings.",
         "Use Command for clear localized routing decisions during agent handoffs.",
         "Overusing Command across all nodes can obscure overall graph topology if not documented.",
         "Command provides clean atomic handoff semantics in multi-agent supervisor systems.",
         ["Creating redundant conditional edge routers when Command can handle it cleanly", "Returning invalid goto target names"]),
        
        ("How do you unit test a single node function in isolation within LangGraph?",
         "Because node functions are plain Python functions that take state and return a dict, you invoke them directly with mock state.",
         "One of the greatest architectural benefits of LangGraph is that node functions are pure or semi-pure Python callables decoupled from graph runtime. To unit test a node, you simply construct a dictionary matching the expected input state and assert on the dictionary returned by the function, without needing to compile or run the full graph.",
         "pytest: test_node_returns_expected_diff -> call node_func({'query': 'test'}) -> assert result == {'status': 'ok'}",
         "def test_process_node():\n    mock_state = {'input': 'hello', 'output': ''}\n    result = process_node(mock_state)\n    assert result == {'output': 'HELLO'}",
         "Tests software engineering testing discipline in agentic systems.",
         "Verify candidate knows how to write fast isolated unit tests for agent logic.",
         "Keep business logic in pure node functions and inject external dependencies via config or mocks.",
         "Running full LLM-connected graphs during unit tests makes test suites slow, costly, and flaky.",
         "Mock LLM responses at the node level to ensure fast, deterministic CI test runs.",
         ["Assuming nodes can only be tested by compiling and running the entire graph", "Testing LLM calls directly in unit tests without mocking"]),
        
        ("What is the role of entry_point in older versions of LangGraph compared to START?",
         "Older versions used set_entry_point('node_name'), while modern LangGraph uses builder.add_edge(START, 'node_name').",
         "In early LangGraph releases (v0.0.x), developers configured the first node using set_entry_point('first_node'). Modern LangGraph unified graph mechanics by introducing virtual START and END constants, treating graph entry as a standard directed edge from START. This provides a consistent mental model across all transitions.",
         "set_entry_point('agent') [Legacy] -> add_edge(START, 'agent') [Modern 2026]",
         "# Modern LangGraph 2026 syntax:\nbuilder.add_edge(START, 'agent_node')\nbuilder.add_edge('agent_node', END)",
         "Tests candidate's currency with modern LangGraph API specifications.",
         "Verify candidate does not use outdated syntax from old blog posts.",
         "Use START and END constants to maintain clean forward compatibility.",
         "Using legacy methods may generate deprecation warnings or fail in upcoming major releases.",
         "Virtual nodes make graph topology rendering symmetrical and clean.",
         ["Using deprecated set_entry_point in new code", "Writing string '__start__' manually"]),
        
        ("How do you handle exceptions in LangGraph nodes to prevent graph crashes?",
         "Wrap risky operations in try-except blocks inside the node and return an error state dictionary for downstream handling.",
         "If an uncaught exception occurs inside a node function, LangGraph immediately halts execution. In production systems, nodes should catch expected operational failures (such as rate limits, network timeouts, or schema parsing errors) and return a state update such as {'error': str(e), 'status': 'failed'}. A conditional edge can then route to a recovery or fallback node.",
         "try: api_call() -> except Exception as e: return {'error': str(e), 'status': 'retry'}",
         "def robust_node(state: State) -> dict:\n    try:\n        output = external_service_call(state['payload'])\n        return {'output': output, 'error': None}\n    except Exception as e:\n        return {'output': None, 'error': f'Failed: {str(e)}'}",
         "Assesses production resilience and error-handling maturity.",
         "Verify candidate builds defensive agent architectures that self-heal or fail gracefully.",
         "Route error states to specialized retry or escalation nodes rather than terminating silently.",
         "Unchecked exceptions terminate customer sessions and cause lost in-flight state.",
         "Returning error state enables the agent to inspect the error message and attempt self-correction.",
         ["Letting raw network exceptions bubble up and crash the graph process", "Ignoring error states in conditional router nodes"]),
        
        ("What is the difference between add_edge and add_conditional_edges?",
         "add_edge creates a deterministic 1-to-1 transition, while add_conditional_edges routes dynamically based on state evaluation.",
         "Deterministic edges (add_edge('node_a', 'node_b')) always transition from node_a to node_b upon completion, regardless of state. Conditional edges (add_conditional_edges('node_a', routing_fn, path_map)) execute routing_fn after node_a finishes, inspecting state variables to dynamically pick one of multiple possible destination nodes.",
         "Deterministic: A -> B | Conditional: A -> routing_fn(state) -> B or C or END",
         "builder.add_edge('fetch_data', 'clean_data') # Deterministic\nbuilder.add_conditional_edges('evaluate_data', check_quality, {'pass': 'save', 'fail': 'retry'}) # Conditional",
         "Tests core understanding of deterministic vs non-deterministic workflow control in LangGraph.",
         "Ensure candidate chooses simple static edges when conditional branching is unnecessary.",
         "Use deterministic edges wherever control flow is fixed to minimize code complexity.",
         "Overusing conditional edges when a static edge suffices makes workflows harder to trace.",
         "Static edges are optimized by the compiler for direct pipeline transitions.",
         ["Writing trivial conditional edge functions that always return the same destination", "Using static edge when branching logic is required"]),
    ]

    # Convert tuples into question dicts
    all_l1_state = l1_state_nodes + l1_state_nodes_extra
    for i, item in enumerate(all_l1_state):
        questions.append({
            "title": item[0],
            "slug": f"langgraph-state-nodes-l1-q{i+1}-{item[0][:30].lower().replace(' ', '-').replace('?', '')}",
            "section_slug": "state-graphs-nodes",
            "tier": "L1",
            "short_answer": item[1],
            "interview_ready_answer": item[2],
            "deep_explanation": f"{item[2]}\n\nArchitectural Note: In LangGraph, nodes are modular execution units. When state flows across edges, the compiler ensures atomic persistence points. Understanding this separation of state data and execution behavior is critical for scaling enterprise multi-step agents.",
            "architecture_notes": item[3],
            "code_example": item[4],
            "why_interviewer_asks": item[5],
            "interviewer_intent": item[6],
            "production_considerations": item[7],
            "failure_modes": item[8],
            "tradeoffs": item[9],
            "common_mistakes": item[10],
            "companies": ["OpenAI", "Google", "Amazon", "Microsoft", "Databricks"][:3],
            "source": source
        })

    return questions
